apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: theinstalytics-com-tls
spec:
  secretName: theinstalytics-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: theinstalytics.com
  dnsNames:
    - theinstalytics.com
    - www.theinstalytics.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - theinstalytics.com
          - www.theinstalytics.com